sudo: false
language: python
python:
  - "3.5"
  - "3.6"
branches:
  only:
    - master
cache: pip
install:
  - travis_retry pip install --upgrade pip
  - travis_retry make dev-install
script:
  - make test
