sudo: false
language: python
python:
- '3.5'
- '3.8'
branches:
  only:
  - master
cache: pip
install:
- travis_retry pip install --upgrade pip
- travis_retry make dev-install
script:
- make test

deploy:
  provider: pypi
  user: edx
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: 3.5
  password:

